services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: evently.sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourSTRONG!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: evently.azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    volumes:
      - azurite_data:/workspace
  
  evently:
    depends_on:
      sqlserver:
        condition: service_started
      azurite:
        condition: service_started
    # provide default value if env variable not set (https://stackoverflow.com/a/70772707/6514532)
    image: "${IMAGE:-eugbyte/eventlyserver:latest}"
    container_name: evently.server
    build:
      context: .
      dockerfile: ./src/Evently.Server/Dockerfile
      labels:
        - "com.microsoft.created-by=rider"
        - "com.microsoft.rider.project-name=Evently.Server"
      args:
        - BUILD_CONFIGURATION=Release
    ports:
      - "4000:8080"
    # order of precedence for env variables
    # https://docs.docker.com/compose/how-tos/environment-variables/envvars-precedence/
    environment:
      ConnectionStrings__WebApiDatabase: "Server=sqlserver,1433;Initial Catalog=evently_docker;User Id=sa;Password=YourSTRONG!Passw0rd;TrustServerCertificate=true;"
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      StorageAccount__AccountName: "evently-dev-images"
      StorageAccount__AzureStorageConnectionString: "DefaultEndpointsProtocol=http;AccountName=account1;AccountKey=key1;BlobEndpoint=http://account1.blob.localhost:10000;QueueEndpoint=http://account1.queue.localhost:10001;TableEndpoint=http://account1.table.localhost:10002;"
      Authentication__Google__ClientId: "<your-google-client-id>"
      Authentication__Google__ClientSecret: "<your-google-client-secret>"
      EmailSettings__ActualFrom: "<your-email@example.com>"
      EmailSettings__SmtpPassword: "<your-app-password>"
      AllowedHosts: "*"

volumes:
  sqlserver_data:
  azurite_data: