services:
  postgres:
    image: postgres:17
    container_name: evently.postgres
    environment:
      POSTGRES_DB: evently_docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  evently:
    depends_on:
      - postgres
    # provide default value if env variable not set (https://stackoverflow.com/a/70772707/6514532)
    image: "${IMAGE:-eugbyte/eventlyserver:latest}"
    container_name: evently.server
    build:
      context: ./src/Evently.Server
      dockerfile: ./Dockerfile
      labels:
        - "com.microsoft.created-by=rider"
        - "com.microsoft.rider.project-name=Evently.Server"
      args:
        - BUILD_CONFIGURATION=Release
    ports:
      - "4000:8080"
    environment:
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      ConnectionStrings__WebApiDatabase: "Database=evently_docker;Server=localhost;Port=5432;Username=postgres;Password=admin;"
      StorageAccount__AccountName: "evently-dev-images"
      StorageAccount__AzureStorageConnectionString: "DefaultEndpointsProtocol=https;AccountName=saeventlydevsea;AccountKey=HEOqV5ViGakHjPwOxWkQFd0iVjyvwPg6MWM7Y2XG/lexPBNsWjolUY5FJgugW69RxmZJcrGb+DyZ+AStJtV5gg==;EndpointSuffix=core.windows.net"
      Authentication__Google__ClientId: "533425050385-fecekp0gl7cc5nt76o0ohgaik7c9l9l1.apps.googleusercontent.com"
      Authentication__Google__ClientSecret: "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"
      EmailSettings__ActualFrom: "hippotechcode@gmail.com"
      EmailSettings__SmtpPassword: "snln ewqe nfyw oyfu"
      AllowedHosts: "*"
volumes:
  postgres_data:
