name: Build evently

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  id-token: write
  contents: read    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Validate Azure CLI can be used
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform validate
        run: |
          cd deploy/Terraform 
          terraform init
          terraform validate
      - name: Terraform plan
        run: |
          cd deploy/Terraform 
          terraform plan
      # Apply step can be skipped for pull requests
      - name: Terraform apply
        run: cd deploy/Terraform && terraform apply -auto-approve
        env:
          TF_VAR_sql_admin_username: ${{ secrets.TF_VAR_SQL_ADMIN_USERNAME }}
          TF_VAR_sql_admin_password: ${{ secrets.TF_VAR_SQL_ADMIN_PASSWORD }}
          TF_VAR_google_client_id: ${{ secrets.TF_VAR_GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.TF_VAR_GOOGLE_CLIENT_SECRET }}
          TF_VAR_email_from: ${{ secrets.TF_VAR_EMAIL_FROM }}
          TF_VAR_smtp_password: ${{ secrets.TF_VAR_SMTP_PASSWORD }}

